version: '3.8'
services:
  training_client:
    build:
      context: ..
      dockerfile: ./train/Dockerfile.training
    volumes:
      - training-data:/app/train/data
    depends_on:
      mongodb:
        condition: service_started
        restart: true
        required: false

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
    profiles:
      - offline

  mongo-express:
    image: mongo-express:latest
    depends_on:
      mongodb:
        condition: service_started
        restart: true
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    profiles:
      - offline

# Define named volumes
volumes:
  mongo-data:
    driver: local
  training-data:
    driver: local